"""phase 5 policy evaluations policy version action execution fields

Revision ID: 37766bb1ab87
Revises: 853a62c9269b
Create Date: 2026-08-26 18:00:05.409108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '37766bb1ab87'
down_revision: Union[str, None] = '853a62c9269b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('recovery_decision_id', sa.UUID(), nullable=True),
    sa.Column('policy_id', sa.UUID(), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_decision_id'], ['recovery_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_evaluations_decision_id', 'policy_evaluations', ['recovery_decision_id'], unique=False)
    op.create_index('ix_policy_evaluations_payment_id', 'policy_evaluations', ['payment_id'], unique=False)
    op.add_column('policies', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('recovery_actions', sa.Column('policy_evaluation_id', sa.UUID(), nullable=True))
    op.add_column('recovery_actions', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.create_index('uq_active_action_per_payment', 'recovery_actions', ['payment_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING', 'VERIFYING_POLICY', 'APPROVED', 'SCHEDULED', 'PROCESSING')"))
    op.create_foreign_key(
        'fk_recovery_actions_policy_evaluation_id',
        'recovery_actions', 'policy_evaluations', ['policy_evaluation_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_recovery_actions_policy_evaluation_id', 'recovery_actions', type_='foreignkey')
    op.drop_index('uq_active_action_per_payment', table_name='recovery_actions', postgresql_where=sa.text("status IN ('PENDING', 'VERIFYING_POLICY', 'APPROVED', 'SCHEDULED', 'PROCESSING')"))
    op.drop_column('recovery_actions', 'idempotency_key')
    op.drop_column('recovery_actions', 'policy_evaluation_id')
    op.drop_column('policies', 'version')
    op.drop_index('ix_policy_evaluations_payment_id', table_name='policy_evaluations')
    op.drop_index('ix_policy_evaluations_decision_id', table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    # ### end Alembic commands ###
