"""phase 4 intelligence fields on recovery decisions

Revision ID: 7dd48c68dfd5
Revises: 7eee978a1443
Create Date: 2026-08-26 16:58:48.381030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7dd48c68dfd5'
down_revision: Union[str, None] = '7eee978a1443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_decisions', sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('recovery_decisions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('recovery_decisions', sa.Column('optimal_window', sa.String(length=16), nullable=True))
    op.add_column('recovery_decisions', sa.Column('data_sufficiency', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_decisions', 'data_sufficiency')
    op.drop_column('recovery_decisions', 'optimal_window')
    op.drop_column('recovery_decisions', 'explanation')
    op.drop_column('recovery_decisions', 'signals')
    # ### end Alembic commands ###
