"""phase 3 webhook events + payment provider columns

Revision ID: 7eee978a1443
Revises: a987b66393be
Create Date: 2026-08-26 16:14:35.929477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7eee978a1443'
down_revision: Union[str, None] = 'a987b66393be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSED', 'FAILED', name='webhookstatus', native_enum=False, length=16), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_webhook_events_provider_event')
    )
    op.create_index('ix_webhook_events_created_at', 'webhook_events', ['created_at'], unique=False)
    op.create_index('ix_webhook_events_provider', 'webhook_events', ['provider'], unique=False)
    op.create_index('ix_webhook_events_status', 'webhook_events', ['status'], unique=False)
    op.add_column('payments', sa.Column('provider_order_id', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('provider_status', sa.String(length=32), nullable=True))
    op.add_column('payments', sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_payments_provider_order_id', 'payments', ['provider_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_provider_order_id', table_name='payments')
    op.drop_column('payments', 'provider_metadata')
    op.drop_column('payments', 'provider_status')
    op.drop_column('payments', 'provider_order_id')
    op.drop_index('ix_webhook_events_status', table_name='webhook_events')
    op.drop_index('ix_webhook_events_provider', table_name='webhook_events')
    op.drop_index('ix_webhook_events_created_at', table_name='webhook_events')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
