"""initial schema

Revision ID: a987b66393be
Revises: 
Create Date: 2026-08-26 15:46:26.137776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a987b66393be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', name='merchantstatus', native_enum=False, length=32), nullable=False),
    sa.Column('environment', sa.Enum('TEST', 'LIVE', name='environment', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_customer_id', name='uq_customers_merchant_external')
    )
    op.create_index('ix_customers_external_customer_id', 'customers', ['external_customer_id'], unique=False)
    op.create_index('ix_customers_merchant_id', 'customers', ['merchant_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('maximum_retries', sa.Integer(), nullable=False),
    sa.Column('recovery_window_days', sa.Integer(), nullable=False),
    sa.Column('minimum_ai_confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('high_value_threshold', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prevent_duplicate_recovery', sa.Boolean(), nullable=False),
    sa.Column('require_policy_approval', sa.Boolean(), nullable=False),
    sa.Column('maintain_audit_log', sa.Boolean(), nullable=False),
    sa.Column('escalate_high_value', sa.Boolean(), nullable=False),
    sa.Column('failure_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_index('ix_policies_merchant_id', 'policies', ['merchant_id'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('transactions', sa.Integer(), nullable=False),
    sa.Column('average_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('failure_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('recovery_window_days', sa.Integer(), nullable=False),
    sa.Column('static_recovery_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ai_recovery_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('static_recovered_revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('ai_recovered_revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('incremental_revenue', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('result_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_simulations_merchant_id', 'simulations', ['merchant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('external_payment_id', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NET_BANKING', name='paymentmethod', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('FAILED', 'QUEUED', 'SCHEDULED', 'PROCESSING', 'RECOVERED', 'HALTED', 'NEEDS_ACTION', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority', native_enum=False, length=16), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'external_payment_id', name='uq_payments_merchant_external')
    )
    op.create_index('ix_payments_customer_id', 'payments', ['customer_id'], unique=False)
    op.create_index('ix_payments_external_payment_id', 'payments', ['external_payment_id'], unique=False)
    op.create_index('ix_payments_merchant_id', 'payments', ['merchant_id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('PAYMENT_FAILED', 'AI_DIAGNOSIS', 'RECOVERY_PREDICTION', 'ACTION_SELECTED', 'POLICY_CHECK', 'RECOVERY_SCHEDULED', 'RECOVERY_EXECUTED', 'PAYMENT_RECOVERED', 'RECOVERY_HALTED', 'CUSTOMER_NOTIFIED', 'POLICY_BLOCKED', 'POLICY_ESCALATED', name='auditeventtype', native_enum=False, length=40), nullable=False),
    sa.Column('category', sa.Enum('AI_DECISION', 'POLICY', 'EXECUTION', 'RESULT', name='auditcategory', native_enum=False, length=32), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'AI_ENGINE', 'OPERATOR', 'MERCHANT', name='actortype', native_enum=False, length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_events_event_type', 'audit_events', ['event_type'], unique=False)
    op.create_index('ix_audit_events_merchant_id', 'audit_events', ['merchant_id'], unique=False)
    op.create_index('ix_audit_events_payment_id', 'audit_events', ['payment_id'], unique=False)
    op.create_table('payment_failures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=False),
    sa.Column('failure_category', sa.Enum('INSUFFICIENT_FUNDS', 'EXPIRED_CARD', 'NETWORK_FAILURE', 'BANK_DECLINE', 'INVALID_DETAILS', 'OTHER', name='failurecategory', native_enum=False, length=40), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_failures_failure_category', 'payment_failures', ['failure_category'], unique=False)
    op.create_index('ix_payment_failures_payment_id', 'payment_failures', ['payment_id'], unique=False)
    op.create_table('recovery_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis', sa.String(length=200), nullable=True),
    sa.Column('ai_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recovery_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recommended_action', sa.Enum('RETRY', 'PAYMENT_UPDATE', 'CUSTOMER_NOTIFICATION', 'ESCALATE', 'STOP', name='recommendedaction', native_enum=False, length=40), nullable=True),
    sa.Column('expected_recovery_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('optimal_recovery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recovery_decisions_payment_id', 'recovery_decisions', ['payment_id'], unique=False)
    op.create_table('recovery_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('RETRY', 'PAYMENT_UPDATE', 'CUSTOMER_NOTIFICATION', 'ESCALATE', 'STOP', name='recommendedaction', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCHEDULED', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'BLOCKED', 'ESCALATED', name='recoveryactionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['recovery_decisions.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recovery_actions_payment_id', 'recovery_actions', ['payment_id'], unique=False)
    op.create_index('ix_recovery_actions_scheduled_at', 'recovery_actions', ['scheduled_at'], unique=False)
    op.create_index('ix_recovery_actions_status', 'recovery_actions', ['status'], unique=False)

    # Append-only guarantee for the audit trail: the database itself rejects
    # UPDATE and DELETE on audit_events (SQLSTATE 55006), so financial history
    # cannot be mutated or erased even by application bugs. The repository
    # layer additionally exposes only insert/read operations.
    op.execute("""
        CREATE OR REPLACE FUNCTION prevent_audit_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'audit_events is append-only: % is not permitted',
                TG_OP USING ERRCODE = '55006';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events;
        CREATE TRIGGER trg_audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION prevent_audit_mutation();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recovery_actions_status', table_name='recovery_actions')
    op.drop_index('ix_recovery_actions_scheduled_at', table_name='recovery_actions')
    op.drop_index('ix_recovery_actions_payment_id', table_name='recovery_actions')
    op.drop_table('recovery_actions')
    op.drop_index('ix_recovery_decisions_payment_id', table_name='recovery_decisions')
    op.drop_table('recovery_decisions')
    op.drop_index('ix_payment_failures_payment_id', table_name='payment_failures')
    op.drop_index('ix_payment_failures_failure_category', table_name='payment_failures')
    op.drop_table('payment_failures')
    op.drop_index('ix_audit_events_payment_id', table_name='audit_events')
    op.drop_index('ix_audit_events_merchant_id', table_name='audit_events')
    op.drop_index('ix_audit_events_event_type', table_name='audit_events')
    op.drop_index('ix_audit_events_created_at', table_name='audit_events')
    # The append-only trigger must be removed before the table can be dropped.
    op.execute("DROP TRIGGER IF EXISTS trg_audit_events_append_only ON audit_events;")
    op.execute("DROP FUNCTION IF EXISTS prevent_audit_mutation();")
    op.drop_table('audit_events')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_merchant_id', table_name='payments')
    op.drop_index('ix_payments_external_payment_id', table_name='payments')
    op.drop_index('ix_payments_customer_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_simulations_merchant_id', table_name='simulations')
    op.drop_table('simulations')
    op.drop_index('ix_policies_merchant_id', table_name='policies')
    op.drop_table('policies')
    op.drop_index('ix_customers_merchant_id', table_name='customers')
    op.drop_index('ix_customers_external_customer_id', table_name='customers')
    op.drop_table('customers')
    op.drop_table('merchants')
    # ### end Alembic commands ###
