"""add merchant razorpay fields

Revision ID: ph9_add_merchant_razorpay_fields
Revises: 37766bb1ab87_phase_5_policy_evaluations_policy_
Create Date: 2026-08-27 01:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ph9_add_merchant_razorpay_fields'
down_revision = '37766bb1ab87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('razorpay_key_id', sa.String(length=100), nullable=True))
    op.add_column('merchants', sa.Column('razorpay_key_secret_encrypted', sa.String(length=500), nullable=True))
    op.add_column('merchants', sa.Column('razorpay_webhook_secret_encrypted', sa.String(length=500), nullable=True))
    op.add_column('merchants', sa.Column('razorpay_webhook_configured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'razorpay_webhook_configured')
    op.drop_column('merchants', 'razorpay_webhook_secret_encrypted')
    op.drop_column('merchants', 'razorpay_key_secret_encrypted')
    op.drop_column('merchants', 'razorpay_key_id')
    # ### end Alembic commands ###