/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppPoliciesRouteImport } from './routes/app.policies'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSimulatorRouteImport } from './routes/app.simulator'
import { Route as AppRecoveryIndexRouteImport } from './routes/app.recovery.index'
import { Route as AppRecoveryIdRouteImport } from './routes/app.recovery.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRoute = AppPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSimulatorRoute = AppSimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoveryIndexRoute = AppRecoveryIndexRouteImport.update({
  id: '/recovery/',
  path: '/recovery/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecoveryIdRoute = AppRecoveryIdRouteImport.update({
  id: '/recovery/$id',
  path: '/recovery/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/policies': typeof AppPoliciesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/recovery/$id': typeof AppRecoveryIdRoute
  '/app/recovery/': typeof AppRecoveryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/policies': typeof AppPoliciesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/recovery/$id': typeof AppRecoveryIdRoute
  '/app/recovery': typeof AppRecoveryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/policies': typeof AppPoliciesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/simulator': typeof AppSimulatorRoute
  '/app/recovery/$id': typeof AppRecoveryIdRoute
  '/app/recovery/': typeof AppRecoveryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/analytics'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/policies'
    | '/app/settings'
    | '/app/simulator'
    | '/app/recovery/$id'
    | '/app/recovery/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/analytics'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/policies'
    | '/app/settings'
    | '/app/simulator'
    | '/app/recovery/$id'
    | '/app/recovery'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/analytics'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/policies'
    | '/app/settings'
    | '/app/simulator'
    | '/app/recovery/$id'
    | '/app/recovery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/policies': {
      id: '/app/policies'
      path: '/policies'
      fullPath: '/app/policies'
      preLoaderRoute: typeof AppPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/simulator': {
      id: '/app/simulator'
      path: '/simulator'
      fullPath: '/app/simulator'
      preLoaderRoute: typeof AppSimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recovery/': {
      id: '/app/recovery/'
      path: '/recovery'
      fullPath: '/app/recovery/'
      preLoaderRoute: typeof AppRecoveryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recovery/$id': {
      id: '/app/recovery/$id'
      path: '/recovery/$id'
      fullPath: '/app/recovery/$id'
      preLoaderRoute: typeof AppRecoveryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPoliciesRoute: typeof AppPoliciesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSimulatorRoute: typeof AppSimulatorRoute
  AppRecoveryIdRoute: typeof AppRecoveryIdRoute
  AppRecoveryIndexRoute: typeof AppRecoveryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPoliciesRoute: AppPoliciesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSimulatorRoute: AppSimulatorRoute,
  AppRecoveryIdRoute: AppRecoveryIdRoute,
  AppRecoveryIndexRoute: AppRecoveryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
